sh run_single.sh $1 $2 antlr
sh run_single.sh $1 $2 avrora
sh run_single.sh $1 $2 batik
sh run_single.sh $1 $2 bloat
sh run_single.sh $1 $2 chart
sh run_single.sh $1 $2 fop
sh run_single.sh $1 $2 hsqldb
sh run_single.sh $1 $2 luindex
sh run_single.sh $1 $2 lusearch
sh run_single.sh $1 $2 pmd
sh run_single.sh $1 $2 sunflow
sh run_single.sh $1 $2 xalan
