sh run_single.sh $1 antlr
sh run_single.sh $1 avrora
sh run_single.sh $1 batik
sh run_single.sh $1 bloat
sh run_single.sh $1 chart
sh run_single.sh $1 fop
sh run_single.sh $1 hsqldb
sh run_single.sh $1 luindex
sh run_single.sh $1 lusearch
sh run_single.sh $1 pmd
sh run_single.sh $1 sunflow
sh run_single.sh $1 xalan
